version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ITEC2024
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - itec-postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  itec-postgres: